//
//  Secrets.swift
//  tesla
//
//  Created by Dakshesh on 2/1/26.
//


//
//  Secrets 2.swift
//  tesla
//
//  Created by Dakshesh on 2/1/26.
//


// Auto-generated by scripts/set-ios-env.js
import Foundation

struct Secrets {
    static let googleMapsApiKey = "AIzaSyC97Ww4ROD5skOe1kD4JQAotzaYKif1D94"
}