const fs = require('fs');
const path = require('path');

// mobile/scripts -> mobile
const mobileRoot = path.join(__dirname, '..');
// mobile -> packages -> repo root
const repoRoot = path.join(mobileRoot, '../..');

const envPath = path.join(repoRoot, '.env');
const targetPath = path.join(mobileRoot, 'ios', 'tesla', 'Secrets.swift');

console.log(`Reading .env from: ${envPath}`);
console.log(`Writing Secrets.swift to: ${targetPath}`);

try {
  let apiKey = '';

  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');

    for (const line of lines) {
      // Simple parser: KEY=VALUE, ignore comments #
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const parts = trimmed.split('=');
      if (parts.length >= 2) {
        const key = parts[0].trim();
        // Join the rest in case value has =
        const value = parts.slice(1).join('=').trim();

        if (key === 'GOOGLE_MAPS_API_KEY') {
          apiKey = value;
          break;
        }
      }
    }
  } else {
    console.warn('No .env file found.');
  }

  if (!apiKey) {
    console.warn(
      'GOOGLE_MAPS_API_KEY not found in .env or empty. Using empty string.'
    );
  }

  const fileContent = `// Auto-generated by scripts/set-ios-env.js
import Foundation

struct Secrets {
    static let googleMapsApiKey = "${apiKey}"
}
`;

  fs.writeFileSync(targetPath, fileContent);
  console.log('Successfully generated Secrets.swift');
} catch (err) {
  console.error('Failed to generate Secrets.swift', err);
  process.exit(1);
}
